# Generated by Django 3.2.2 on 2021-06-13 16:25

from django.db import migrations, models
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_alter_profile_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.FileField(upload_to=uploads.models.cv_convert),
        ),
    ]
